### ISSUE TITLE
[Back] User improvements

### ISSUE THREAD

**Issue by arkanoryn** [arkanoryn/remote_day#17]
We want to limit the actions that a user can do:

- [x] Creating an event can only be done by authenticated user
- [x] New created event are automagically linked to the current_user
- [x] A user can only create one (1) event/day
- [x] User needs to be authenticated to fetch events
